ALTER TABLE execution_jobs ADD COLUMN IF NOT EXISTS attempt_count INT NOT NULL DEFAULT 0;
ALTER TABLE execution_jobs ADD COLUMN IF NOT EXISTS max_attempts INT NOT NULL DEFAULT 3;
ALTER TABLE execution_jobs ADD COLUMN IF NOT EXISTS last_error TEXT;
