apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mandoforge-remote-computer-state
  annotations:
    mandoforge.io/profile: remote-computer-state
    mandoforge.io/provider: juicefs
spec:
  storageClassName: ""
  volumeName: mandoforge-remote-computer-state-juicefs-pv
