apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mandoforge-remote-computer-state
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
