use std::fmt::Write;

use serde_json::Value;

use crate::{
    AppError, OntologyReleaseCatalogV1, OntologySdkCatalogAction, OntologySdkCatalogObject,
    OntologySdkCatalogProperty, OntologySdkCatalogRelation,
};

pub(crate) fn generate_typescript_sdk(
    application_id: uuid::Uuid,
    catalog: &OntologyReleaseCatalogV1,
) -> Result<String, AppError> {
    if catalog.schema != crate::ONTOLOGY_RELEASE_CATALOG_SCHEMA {
        return Err(AppError::forbidden(
            "ontology SDK TypeScript catalog schema is unsupported",
        ));
    }
    if catalog
        .actions
        .iter()
        .any(|action| action.execution_mode != "proposal_only")
    {
        return Err(AppError::forbidden(
            "ontology SDK TypeScript generation only supports proposal_only actions",
        ));
    }

    let mut output = String::new();
    writeln!(
        output,
        "/* Generated by MandoForge from an immutable ontology SDK manifest. */"
    )
    .unwrap();
    writeln!(
        output,
        "/* This surface is read/propose-only; do not add write methods. */\n"
    )
    .unwrap();
    writeln!(
        output,
        "export type JsonRecord = Record<string, unknown>;\n"
    )
    .unwrap();
    writeln!(
        output,
        "export type OntologyActionApprovalRequired = {{ status: \"approval_required\"; [key: string]: unknown }};"
    )
    .unwrap();
    writeln!(
        output,
        "export type OntologyActionProposalCreated = {{ status: \"proposal_created\"; [key: string]: unknown }};"
    )
    .unwrap();
    writeln!(
        output,
        "export type OntologyActionResult = OntologyActionApprovalRequired | OntologyActionProposalCreated;\n"
    )
    .unwrap();
    writeln!(
        output,
        "export interface MandoForgeConsumerReadQuery {{ taskGrantId?: string; objectId?: string; relationApiName?: string }}\n"
    )
    .unwrap();
    writeln!(
        output,
        "export const MANDOFORGE_APPLICATION_ID: string = {};\n",
        json_string_literal(&application_id.to_string())
    )
    .unwrap();
    writeln!(
        output,
        "export interface MandoForgeOntologySdkOptions {{ baseUrl: string; headers?: Record<string, string> }}\n"
    )
    .unwrap();

    for object in &catalog.objects {
        write_object_types(&mut output, object);
    }
    for relation in &catalog.relations {
        write_relation_type(&mut output, relation);
    }
    for action in &catalog.actions {
        write_action_types(&mut output, action)?;
    }

    writeln!(output, "export class MandoForgeOntologySdk {{").unwrap();
    writeln!(
        output,
        "  private readonly baseUrl: string;\n  private readonly headers: Record<string, string>;"
    )
    .unwrap();
    writeln!(
        output,
        "\n  public constructor(options: MandoForgeOntologySdkOptions) {{\n    this.baseUrl = options.baseUrl.replace(/\\/+$/, \"\");\n    this.headers = options.headers ?? {{}};\n  }}"
    )
    .unwrap();
    writeln!(
        output,
        "\n  private withQuery(path: string, query: Record<string, string | undefined>): string {{\n    const params = new URLSearchParams();\n    for (const [key, value] of Object.entries(query)) {{\n      if (value !== undefined) params.set(key, value);\n    }}\n    const encoded = params.toString();\n    return encoded.length === 0 ? path : `${{path}}?${{encoded}}`;\n  }}"
    )
    .unwrap();
    writeln!(
        output,
        "\n  private async request<T>(path: string, init?: RequestInit): Promise<T> {{\n    const headers = new Headers(this.headers);\n    headers.set(\"accept\", \"application/json\");\n    if (init?.body !== undefined) headers.set(\"content-type\", \"application/json\");\n    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));\n    const response = await fetch(`${{this.baseUrl}}${{path}}`, {{ ...init, headers }});\n    if (!response.ok) throw new Error(`MandoForge ontology SDK request failed (${{response.status}})`);\n    return await response.json() as T;\n  }}"
    )
    .unwrap();

    writeln!(output, "\n  public readonly objects = {{").unwrap();
    for object in &catalog.objects {
        let object_type = ts_type_name(&object.api_name);
        let object_literal = json_string_literal(&object.api_name);
        let object_path = &object.api_name;
        writeln!(
            output,
            "    {object_literal}: {{\n      list: (query: MandoForgeConsumerReadQuery = {{}}): Promise<{object_type}[]> =>\n        this.request<{object_type}[]>(this.withQuery(`/api/ontology-sdk/applications/${{MANDOFORGE_APPLICATION_ID}}/objects/{object_path}`, {{ task_grant_id: query.taskGrantId }})),\n      get: (id: string, query: MandoForgeConsumerReadQuery = {{}}): Promise<{object_type}> =>\n        this.request<{object_type}>(this.withQuery(`/api/ontology-sdk/applications/${{MANDOFORGE_APPLICATION_ID}}/objects/{object_path}/${{encodeURIComponent(id)}}`, {{ task_grant_id: query.taskGrantId }})),\n    }},"
        )
        .unwrap();
    }
    writeln!(output, "  }} as const;\n").unwrap();

    writeln!(output, "  public readonly relations = {{").unwrap();
    for relation in &catalog.relations {
        let relation_type = format!("{}Relation", ts_type_name(&relation.api_name));
        let relation_literal = json_string_literal(&relation.api_name);
        writeln!(
            output,
            "    {relation_literal}: {{\n      list: (query: MandoForgeConsumerReadQuery = {{}}): Promise<{relation_type}[]> =>\n        this.request<{relation_type}[]>(this.withQuery(`/api/ontology-sdk/applications/${{MANDOFORGE_APPLICATION_ID}}/relations`, {{ task_grant_id: query.taskGrantId, object_id: query.objectId, relation_api_name: {relation_literal} }})),\n    }},"
        )
        .unwrap();
    }
    writeln!(output, "  }} as const;\n").unwrap();

    writeln!(output, "  public readonly actions = {{").unwrap();
    for action in &catalog.actions {
        let action_type = ts_type_name(&action.api_name);
        let action_literal = json_string_literal(&action.api_name);
        let action_path = &action.api_name;
        writeln!(
            output,
            "    {action_literal}: {{\n      propose: (input: {action_type}ProposalRequest): Promise<OntologyActionResult> =>\n        this.request<OntologyActionResult>(`/api/ontology-sdk/applications/${{MANDOFORGE_APPLICATION_ID}}/actions/{action_path}`, {{\n          method: \"POST\",\n          body: JSON.stringify({{ session_id: input.sessionId, task_grant_id: input.taskGrantId, context_packet_id: input.contextPacketId, parameters: input.parameters }}),\n        }}),\n    }},"
        )
        .unwrap();
    }
    writeln!(output, "  }} as const;\n}}").unwrap();

    Ok(output)
}

fn write_object_types(output: &mut String, object: &OntologySdkCatalogObject) {
    let type_name = ts_type_name(&object.api_name);
    writeln!(output, "export interface {type_name}Properties {{").unwrap();
    for property in &object.properties {
        write_property(output, property, 2, true);
    }
    writeln!(output, "}}\n").unwrap();
    writeln!(output, "export interface {type_name} {{").unwrap();
    writeln!(output, "  readonly id: string;").unwrap();
    writeln!(output, "  readonly api_name: string;").unwrap();
    writeln!(output, "  readonly object_type: string;").unwrap();
    writeln!(output, "  readonly object_key: string;").unwrap();
    writeln!(output, "  readonly title: string;").unwrap();
    writeln!(output, "  readonly summary: string;").unwrap();
    writeln!(output, "  readonly properties: {type_name}Properties;").unwrap();
    writeln!(output, "}}\n").unwrap();
}

fn write_relation_type(output: &mut String, relation: &OntologySdkCatalogRelation) {
    let type_name = ts_type_name(&relation.api_name);
    writeln!(output, "export interface {type_name}Relation {{").unwrap();
    writeln!(output, "  readonly id: string;").unwrap();
    writeln!(output, "  readonly api_name: string;").unwrap();
    writeln!(output, "  readonly relation_type: string;").unwrap();
    writeln!(output, "  readonly from_object_id: string;").unwrap();
    writeln!(output, "  readonly to_object_id: string;").unwrap();
    writeln!(output, "}}\n").unwrap();
}

fn write_action_types(
    output: &mut String,
    action: &OntologySdkCatalogAction,
) -> Result<(), AppError> {
    let type_name = ts_type_name(&action.api_name);
    writeln!(output, "export interface {type_name}Parameters {{").unwrap();
    let (properties, required) = schema_properties(&action.input_schema)?;
    for (name, schema) in properties {
        let optional = !required.contains(&name);
        write_schema_property(output, name, schema, 2, optional)?;
    }
    writeln!(output, "}}\n").unwrap();
    writeln!(output, "export interface {type_name}ProposalRequest {{").unwrap();
    writeln!(output, "  readonly sessionId: string;").unwrap();
    writeln!(output, "  readonly taskGrantId: string;").unwrap();
    writeln!(output, "  readonly contextPacketId: string;").unwrap();
    writeln!(output, "  readonly parameters: {type_name}Parameters;").unwrap();
    writeln!(output, "}}\n").unwrap();
    Ok(())
}

type SchemaProperties<'a> = (Vec<(&'a str, &'a Value)>, Vec<&'a str>);

fn schema_properties(schema: &Value) -> Result<SchemaProperties<'_>, AppError> {
    let object = schema.as_object().ok_or_else(|| {
        AppError::forbidden("ontology SDK action input schema must be a JSON object")
    })?;
    let (properties, required) = if let Some(properties) = object.get("properties") {
        let properties = properties.as_object().ok_or_else(|| {
            AppError::forbidden("ontology SDK action input schema properties must be an object")
        })?;
        let required = object
            .get("required")
            .and_then(Value::as_array)
            .map(|values| values.iter().filter_map(Value::as_str).collect::<Vec<_>>())
            .unwrap_or_default();
        (properties, required)
    } else {
        let mut properties = object
            .iter()
            .filter(|(name, _)| {
                !matches!(
                    name.as_str(),
                    "type" | "required" | "$schema" | "additionalProperties"
                )
            })
            .map(|(name, value)| (name.as_str(), value))
            .collect::<Vec<_>>();
        properties.sort_by(|left, right| left.0.cmp(right.0));
        let required = properties
            .iter()
            .filter(|(_, declaration)| {
                declaration
                    .get("required")
                    .and_then(Value::as_bool)
                    .unwrap_or(true)
            })
            .map(|(name, _)| *name)
            .collect();
        return Ok((properties, required));
    };
    let mut properties = properties
        .iter()
        .map(|(name, value)| (name.as_str(), value))
        .collect::<Vec<_>>();
    properties.sort_by(|left, right| left.0.cmp(right.0));
    Ok((properties, required))
}

fn write_property(
    output: &mut String,
    property: &OntologySdkCatalogProperty,
    indent: usize,
    readonly: bool,
) {
    let prefix = " ".repeat(indent);
    let optional = if property.nullable { "?" } else { "" };
    let readonly = if readonly { "readonly " } else { "" };
    let value_type = primitive_type(&property.value_type);
    let nullable = if property.nullable { " | null" } else { "" };
    writeln!(
        output,
        "{prefix}{readonly}{}{}: {value_type}{nullable};",
        json_string_literal(&property.api_name),
        optional
    )
    .unwrap();
}

fn write_schema_property(
    output: &mut String,
    name: &str,
    schema: &Value,
    indent: usize,
    optional: bool,
) -> Result<(), AppError> {
    let prefix = " ".repeat(indent);
    let optional = if optional { "?" } else { "" };
    writeln!(
        output,
        "{prefix}readonly {}{}: {};",
        json_string_literal(name),
        optional,
        schema_type(schema)
    )
    .unwrap();
    Ok(())
}

fn schema_type(schema: &Value) -> String {
    match schema {
        Value::String(value) => primitive_type(value),
        Value::Object(object) => {
            if let Some(values) = object.get("enum").and_then(Value::as_array) {
                let variants = values
                    .iter()
                    .filter(|value| {
                        object
                            .get("type")
                            .and_then(Value::as_str)
                            .is_none_or(|expected| schema_value_matches_type(value, expected))
                    })
                    .map(Value::to_string)
                    .collect::<Vec<_>>();
                return if variants.is_empty() {
                    "never".to_string()
                } else {
                    variants.join(" | ")
                };
            }
            match object.get("type").and_then(Value::as_str) {
                Some("array") => object
                    .get("items")
                    .map(schema_type)
                    .map(|value| format!("Array<{value}>"))
                    .unwrap_or_else(|| "Array<unknown>".to_string()),
                Some("object") => object
                    .get("properties")
                    .and_then(|value| schema_inline_object(value, object.get("required")))
                    .unwrap_or_else(|| "JsonRecord".to_string()),
                Some(value) => primitive_type(value),
                None if object.get("properties").is_some() => object
                    .get("properties")
                    .and_then(|value| schema_inline_object(value, object.get("required")))
                    .unwrap_or_else(|| "JsonRecord".to_string()),
                _ => "unknown".to_string(),
            }
        }
        _ => "unknown".to_string(),
    }
}

fn schema_value_matches_type(value: &Value, expected: &str) -> bool {
    match expected.trim().to_ascii_lowercase().as_str() {
        "string" | "text" | "uuid" | "date" | "timestamp" | "datetime" => value.is_string(),
        "integer" | "int" | "int32" | "int64" => schema_integer_literal(value),
        "number" | "decimal" | "float" | "double" => value.is_number(),
        "boolean" | "bool" => value.is_boolean(),
        "object" | "json" => value.is_object(),
        "array" => value.is_array(),
        "null" => value.is_null(),
        _ => false,
    }
}

fn schema_integer_literal(value: &Value) -> bool {
    if value.as_i64().is_some() || value.as_u64().is_some() {
        return true;
    }
    value.as_f64().is_some_and(|number| {
        number.is_finite()
            && number.fract() == 0.0
            && (((-9_223_372_036_854_775_808.0..9_223_372_036_854_775_808.0).contains(&number)
                && (number as i64) as f64 == number)
                || ((0.0..18_446_744_073_709_551_616.0).contains(&number)
                    && (number as u64) as f64 == number))
    })
}

fn schema_inline_object(properties: &Value, required: Option<&Value>) -> Option<String> {
    let properties = properties.as_object()?;
    let required = required
        .and_then(Value::as_array)
        .map(|values| values.iter().filter_map(Value::as_str).collect::<Vec<_>>())
        .unwrap_or_default();
    let mut output = String::from("{ ");
    for (name, schema) in properties {
        let optional = if required.contains(&name.as_str()) {
            ""
        } else {
            "?"
        };
        write!(
            output,
            "readonly {}{}: {}; ",
            json_string_literal(name),
            optional,
            schema_type(schema)
        )
        .unwrap();
    }
    output.push('}');
    Some(output)
}

fn primitive_type(value: &str) -> String {
    match value.trim().to_ascii_lowercase().as_str() {
        "string" | "text" | "uuid" | "date" | "timestamp" | "datetime" => "string",
        "integer" | "int" | "int32" | "int64" | "number" | "decimal" | "float" | "double" => {
            "number"
        }
        "boolean" | "bool" => "boolean",
        "object" | "json" => "JsonRecord",
        "array" => "Array<unknown>",
        "null" => "null",
        _ => "unknown",
    }
    .to_string()
}

fn ts_type_name(api_name: &str) -> String {
    let mut chars = api_name.chars();
    match chars.next() {
        Some(first) => format!(
            "{}{}",
            first.to_ascii_uppercase(),
            chars.collect::<String>()
        ),
        None => "OntologyValue".to_string(),
    }
}

fn json_string_literal(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        ONTOLOGY_RELEASE_CATALOG_SCHEMA, OntologySdkCatalogAction, OntologySdkCatalogObject,
        OntologySdkCatalogProperty, OntologySdkCatalogRelation,
    };

    fn fixture_catalog() -> OntologyReleaseCatalogV1 {
        OntologyReleaseCatalogV1 {
            schema: ONTOLOGY_RELEASE_CATALOG_SCHEMA.to_string(),
            domain_scope: "commerce".to_string(),
            objects: vec![
                OntologySdkCatalogObject {
                    stable_key: "object:Customer".to_string(),
                    api_name: "Customer".to_string(),
                    object_type: "Customer".to_string(),
                    properties: vec![
                        OntologySdkCatalogProperty {
                            stable_key: "object:Customer:property:created_at".to_string(),
                            source_name: "created_at".to_string(),
                            api_name: "createdAt".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                        OntologySdkCatalogProperty {
                            stable_key: "object:Customer:property:email".to_string(),
                            source_name: "email".to_string(),
                            api_name: "email".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                        OntologySdkCatalogProperty {
                            stable_key: "object:Customer:property:id".to_string(),
                            source_name: "id".to_string(),
                            api_name: "id".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                        OntologySdkCatalogProperty {
                            stable_key: "object:Customer:property:name".to_string(),
                            source_name: "name".to_string(),
                            api_name: "name".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                    ],
                    primary_key_api_name: None,
                },
                OntologySdkCatalogObject {
                    stable_key: "object:SupportTicket".to_string(),
                    api_name: "SupportTicket".to_string(),
                    object_type: "SupportTicket".to_string(),
                    properties: vec![
                        OntologySdkCatalogProperty {
                            stable_key: "object:SupportTicket:property:customer_id".to_string(),
                            source_name: "customer_id".to_string(),
                            api_name: "customerId".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                        OntologySdkCatalogProperty {
                            stable_key: "object:SupportTicket:property:id".to_string(),
                            source_name: "id".to_string(),
                            api_name: "id".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                        OntologySdkCatalogProperty {
                            stable_key: "object:SupportTicket:property:order_id".to_string(),
                            source_name: "order_id".to_string(),
                            api_name: "orderId".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                        OntologySdkCatalogProperty {
                            stable_key: "object:SupportTicket:property:status".to_string(),
                            source_name: "status".to_string(),
                            api_name: "status".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                        OntologySdkCatalogProperty {
                            stable_key: "object:SupportTicket:property:topic".to_string(),
                            source_name: "topic".to_string(),
                            api_name: "topic".to_string(),
                            value_type: "string".to_string(),
                            nullable: true,
                        },
                    ],
                    primary_key_api_name: None,
                },
            ],
            relations: vec![OntologySdkCatalogRelation {
                stable_key: "relation:Customer:creates:SupportTicket".to_string(),
                api_name: "customerCreatesSupportTicket".to_string(),
                from_object_api_name: "Customer".to_string(),
                relation_type: "creates".to_string(),
                to_object_api_name: "SupportTicket".to_string(),
            }],
            actions: vec![OntologySdkCatalogAction {
                stable_key: "action:commerce.adjust_inventory".to_string(),
                api_name: "adjustInventory".to_string(),
                runtime_name: "commerce.adjust_inventory".to_string(),
                contract_digest: "sha256:fixture".to_string(),
                execution_mode: "proposal_only".to_string(),
                target_object_api_name: "SupportTicket".to_string(),
                input_schema: serde_json::json!({
                    "delta_quantity": "number",
                    "inventory_item_id": "string",
                    "reason": "string",
                }),
                approval_required: false,
            }],
        }
    }

    #[test]
    fn generated_sdk_is_deterministic_strict_and_proposal_only() {
        let catalog = fixture_catalog();
        assert!(!catalog.actions[0].approval_required);
        let first = generate_typescript_sdk(uuid::Uuid::nil(), &catalog).expect("first output");
        let second = generate_typescript_sdk(uuid::Uuid::nil(), &catalog).expect("second output");
        assert_eq!(first, second);
        assert_eq!(
            first,
            include_str!("../../../examples/mandoforge-osdk-typescript/src/generated/fixture.ts")
        );
        assert!(first.contains("unknown"));
        assert!(!first.contains(": any"));
        for forbidden in ["create:", "update:", "delete:", "approve:", "commit:"] {
            assert!(
                !first.contains(forbidden),
                "generated forbidden method: {forbidden}"
            );
        }
        assert!(first.contains("propose:"));
        assert!(first.contains("export const MANDOFORGE_APPLICATION_ID: string = \"00000000-0000-0000-0000-000000000000\";"));
        assert!(!first.contains("applicationId: string"));
        assert!(first.contains("status: \"approval_required\""));
        assert!(first.contains("status: \"proposal_created\""));
        assert!(
            first.find("if (!response.ok)").expect("status check")
                < first.find("response.json()").expect("JSON parse")
        );
    }

    #[test]
    fn generated_sdk_honors_optional_shorthand_action_parameters() {
        let mut catalog = fixture_catalog();
        catalog.actions[0].input_schema = serde_json::json!({
            "required_name": "string",
            "optional_note": {"type": "string", "required": false},
            "priority": {"type": "number", "enum": [1, 2.5], "required": false},
            "integral_priority": {"type": "integer", "enum": [1.0], "required": false},
            "approved": {"type": "boolean", "enum": [true, false], "required": false},
            "mixed_number": {"type": "number", "enum": [1, "invalid", 2.5], "required": false}
        });

        let output = generate_typescript_sdk(uuid::Uuid::nil(), &catalog).expect("SDK output");

        assert!(output.contains("readonly \"required_name\": string;"));
        assert!(output.contains("readonly \"optional_note\"?: string;"));
        assert!(output.contains("readonly \"priority\"?: 1 | 2.5;"));
        assert!(output.contains("readonly \"integral_priority\"?: 1.0;"));
        assert!(output.contains("readonly \"approved\"?: true | false;"));
        assert!(output.contains("readonly \"mixed_number\"?: 1 | 2.5;"));
    }
}
