use std::{collections::HashMap, sync::Arc};

use sqlx::PgPool;
use tokio::sync::RwLock;
use uuid::Uuid;

use crate::{
    Agent, AgentHandoffAssignment, AgentHandoffEvent, AgentRelease, AgentRuntimeProfile,
    AgentTeammate, AgentVersion, Approval, ApprovalCommitToken, ApprovalEscalationRule,
    ApprovalGroup, ApprovalNotificationChannelPolicy, Artifact, AuditLog, CodexAppServerRun,
    ContextPacket, CostAlertRoute, Environment, EvalCase, EvalDataset, EvalRun, ManagerAgentPlan,
    McpServerRecord, Membership, MemoryWritebackCandidate, OntologyRelease,
    OntologyReleaseWorkflowTrigger, OntologySdkApplication, Organization, PolicyRevision, Project,
    ProjectGitHubBinding, ProviderAccess, ProviderRecord, RemoteComputer, RemoteComputerAttachment,
    RemoteComputerJobAssignment, RemoteComputerLease, RemoteComputerSidecarHeartbeat,
    RemoteComputerStateLock, SecretRecord, SemanticLink, SemanticObject, SemanticSource, Session,
    SessionEvent, SessionLoopJob, SessionThread, Squad, SquadMember, TaskGrant, Team,
    TenantInvitation, ToolCall, UsageRollup, WorkItem, WorkItemActivityEntry, WorkItemAssignment,
    WorkItemReview, WorkflowDefinition, WorkflowPackBinding, WorkflowPackInstallation,
    WorkflowPackProfileAsset, WorkflowPackRuntimeObject, WorkflowRun, WorkflowStepRun,
    WorkflowTransition,
};

#[derive(Default)]
pub(crate) struct MemoryStore {
    pub(crate) agents: HashMap<Uuid, Agent>,
    pub(crate) agent_runtime_profiles: HashMap<Uuid, AgentRuntimeProfile>,
    pub(crate) environments: HashMap<Uuid, Environment>,
    pub(crate) agent_releases: HashMap<Uuid, AgentRelease>,
    pub(crate) policy_revisions: HashMap<Uuid, PolicyRevision>,
    pub(crate) secret_records: HashMap<Uuid, SecretRecord>,
    pub(crate) agent_versions: HashMap<Uuid, Vec<AgentVersion>>,
    pub(crate) sessions: HashMap<Uuid, Session>,
    pub(crate) events: HashMap<Uuid, Vec<SessionEvent>>,
    pub(crate) session_loop_jobs: HashMap<Uuid, SessionLoopJob>,
    pub(crate) session_threads: HashMap<Uuid, SessionThread>,
    pub(crate) approvals: HashMap<Uuid, Approval>,
    pub(crate) approval_commit_tokens: HashMap<Uuid, ApprovalCommitToken>,
    pub(crate) approval_groups: HashMap<Uuid, ApprovalGroup>,
    pub(crate) approval_escalation_rules: HashMap<Uuid, ApprovalEscalationRule>,
    pub(crate) approval_notification_channel_policies:
        HashMap<Uuid, ApprovalNotificationChannelPolicy>,
    pub(crate) artifacts: HashMap<Uuid, Artifact>,
    pub(crate) tool_calls: HashMap<Uuid, ToolCall>,
    pub(crate) audit_logs: HashMap<Uuid, AuditLog>,
    pub(crate) cost_alert_routes: HashMap<Uuid, CostAlertRoute>,
    pub(crate) organizations: HashMap<Uuid, Organization>,
    pub(crate) teams: HashMap<Uuid, Team>,
    pub(crate) projects: HashMap<Uuid, Project>,
    pub(crate) agent_teammates: HashMap<Uuid, AgentTeammate>,
    pub(crate) squads: HashMap<Uuid, Squad>,
    pub(crate) squad_members: HashMap<Uuid, SquadMember>,
    pub(crate) work_items: HashMap<Uuid, WorkItem>,
    pub(crate) work_item_activity_entries: HashMap<Uuid, WorkItemActivityEntry>,
    pub(crate) work_item_assignments: HashMap<Uuid, WorkItemAssignment>,
    pub(crate) work_item_reviews: HashMap<Uuid, WorkItemReview>,
    pub(crate) memberships: HashMap<Uuid, Membership>,
    pub(crate) tenant_invitations: HashMap<Uuid, TenantInvitation>,
    pub(crate) provider_access: HashMap<Uuid, ProviderAccess>,
    pub(crate) providers: HashMap<Uuid, ProviderRecord>,
    pub(crate) mcp_servers: HashMap<Uuid, McpServerRecord>,
    pub(crate) eval_datasets: HashMap<Uuid, EvalDataset>,
    pub(crate) eval_cases: HashMap<Uuid, EvalCase>,
    pub(crate) eval_runs: HashMap<Uuid, EvalRun>,
    pub(crate) usage_rollups: HashMap<Uuid, UsageRollup>,
    pub(crate) codex_app_server_runs: HashMap<Uuid, CodexAppServerRun>,
    pub(crate) remote_computers: HashMap<Uuid, RemoteComputer>,
    pub(crate) remote_computer_leases: HashMap<Uuid, RemoteComputerLease>,
    pub(crate) remote_computer_attachments: HashMap<Uuid, RemoteComputerAttachment>,
    pub(crate) remote_computer_job_assignments: HashMap<Uuid, RemoteComputerJobAssignment>,
    pub(crate) remote_computer_state_locks: HashMap<Uuid, RemoteComputerStateLock>,
    pub(crate) remote_computer_sidecar_heartbeats: HashMap<Uuid, RemoteComputerSidecarHeartbeat>,
    pub(crate) agent_handoff_assignments: HashMap<Uuid, AgentHandoffAssignment>,
    pub(crate) agent_handoff_events: HashMap<Uuid, AgentHandoffEvent>,
    pub(crate) manager_agent_plans: HashMap<Uuid, ManagerAgentPlan>,
    pub(crate) workflow_pack_installations: HashMap<Uuid, WorkflowPackInstallation>,
    pub(crate) workflow_pack_profile_assets: HashMap<Uuid, WorkflowPackProfileAsset>,
    pub(crate) workflow_pack_bindings: HashMap<Uuid, WorkflowPackBinding>,
    pub(crate) workflow_pack_runtime_objects: HashMap<Uuid, WorkflowPackRuntimeObject>,
    pub(crate) workflow_definitions: HashMap<Uuid, WorkflowDefinition>,
    pub(crate) workflow_runs: HashMap<Uuid, WorkflowRun>,
    pub(crate) workflow_step_runs: HashMap<Uuid, WorkflowStepRun>,
    pub(crate) workflow_transitions: HashMap<Uuid, WorkflowTransition>,
    pub(crate) task_grants: HashMap<Uuid, TaskGrant>,
    pub(crate) semantic_sources: HashMap<Uuid, SemanticSource>,
    pub(crate) semantic_objects: HashMap<Uuid, SemanticObject>,
    pub(crate) semantic_links: HashMap<Uuid, SemanticLink>,
    pub(crate) ontology_releases: HashMap<Uuid, OntologyRelease>,
    pub(crate) ontology_release_workflow_triggers: HashMap<Uuid, OntologyReleaseWorkflowTrigger>,
    pub(crate) ontology_sdk_applications: HashMap<Uuid, OntologySdkApplication>,
    pub(crate) context_packets: HashMap<Uuid, ContextPacket>,
    pub(crate) memory_writeback_candidates: HashMap<Uuid, MemoryWritebackCandidate>,
    pub(crate) project_github_bindings: HashMap<Uuid, ProjectGitHubBinding>,
}

#[derive(Clone)]
pub(crate) enum StoreBackend {
    Memory(Arc<RwLock<MemoryStore>>),
    Postgres(PgPool),
}
