#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://127.0.0.1:8787}"
EVIDENCE_DIR="${EVIDENCE_DIR:-.mandoforge/stage2-controller-drill-evidence}"
STAGE2_MOCK_CONTROLLER_PORT="${STAGE2_MOCK_CONTROLLER_PORT:-18080}"
STAGE2_MOCK_CONTROLLER_HOST="${STAGE2_MOCK_CONTROLLER_HOST:-127.0.0.1}"
RUN_DRILL_ACTIONS="${RUN_STAGE2_CONTROLLER_DRILL_ACTIONS:-0}"
MOCK_BASE_URL="http://$STAGE2_MOCK_CONTROLLER_HOST:$STAGE2_MOCK_CONTROLLER_PORT"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Stage 2 controller drill requires $1" >&2
    exit 1
  fi
}

require_cmd node
require_cmd curl
require_cmd jq

if ! curl -fsS "$BASE_URL/healthz" >/dev/null; then
  echo "Stage 2 controller drill requires a running MandoForge API at $BASE_URL" >&2
  exit 1
fi

node scripts/stage2-mock-controller.js &
mock_pid="$!"
cleanup() {
  kill "$mock_pid" >/dev/null 2>&1 || true
}
trap cleanup EXIT

for _ in $(seq 1 50); do
  if curl -fsS "$MOCK_BASE_URL/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 0.1
done

curl -fsS "$MOCK_BASE_URL/healthz" >/dev/null

export ALLOW_BLOCKED="${ALLOW_BLOCKED:-1}"
export RUN_STAGE2_PRODUCTION_VALIDATIONS=1
export VERIFY_STAGE2_VALIDATION_COVERAGE="${VERIFY_STAGE2_VALIDATION_COVERAGE:-1}"
export EVIDENCE_DIR

export MANDOFORGE_TENANT_ROUTING_CONTROLLER_REQUIRED=true
export MANDOFORGE_TENANT_ROUTING_CONTROLLER_URL="$MOCK_BASE_URL/tenant/routing/validate"
export MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_REQUIRED=true
export MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_URL="$MOCK_BASE_URL/provider/deployment/validate"
export MANDOFORGE_PROVIDER_ROLLOUT_CONTROLLER_URL="$MOCK_BASE_URL/provider/rollout/apply"
export MANDOFORGE_PROVIDER_ROLLOUT_ROLLBACK_CONTROLLER_URL="$MOCK_BASE_URL/provider/rollout/rollback"
export MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_REQUIRED=true
export MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_URL="$MOCK_BASE_URL/policy/rollout/orchestration/validate"
export MANDOFORGE_KMS_RECOVERY_CONTROLLER_REQUIRED=true
export MANDOFORGE_KMS_RECOVERY_CONTROLLER_URL="$MOCK_BASE_URL/vault/kms/recovery/validate"
export MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_REQUIRED=true
export MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_URL="$MOCK_BASE_URL/worker/load/validate"
export MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_REQUIRED=true
export MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_URL="$MOCK_BASE_URL/remote-computer/state-sync/validate"
export MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_REQUIRED=true
export MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_URL="$MOCK_BASE_URL/remote-computer/sidecar/validate"
export MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_REQUIRED=true
export MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_URL="$MOCK_BASE_URL/approval-notification/deployment/validate"
export MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_REQUIRED=true
export MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_URL="$MOCK_BASE_URL/approval-notification/ops/validate"
export MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_REQUIRED=true
export MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_URL="$MOCK_BASE_URL/mcp/deployment/validate"
export MANDOFORGE_MCP_ROLLOUT_CONTROLLER_REQUIRED=true
export MANDOFORGE_MCP_ROLLOUT_CONTROLLER_URL="$MOCK_BASE_URL/mcp/rollout/apply"
export MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_REQUIRED=true
export MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_URL="$MOCK_BASE_URL/mcp/rollout/rollback"
export MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_REQUIRED=true
export MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_URL="$MOCK_BASE_URL/codex-app-server/deployment/validate"
export MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_REQUIRED=true
export MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_URL="$MOCK_BASE_URL/codex-app-server/ops/validate"
export MANDOFORGE_AGENT_RELEASE_CONTROLLER_REQUIRED=true
export MANDOFORGE_AGENT_RELEASE_CONTROLLER_URL="$MOCK_BASE_URL/agents/releases/rollout/apply"
export MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_REQUIRED=true
export MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_URL="$MOCK_BASE_URL/agents/releases/deployment/validate"
export MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_REQUIRED=true
export MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_URL="$MOCK_BASE_URL/agents/releases/orchestration/validate"
export MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_REQUIRED=true
export MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_URL="$MOCK_BASE_URL/agents/releases/rollout/rollback"
export MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_REQUIRED=true
export MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_URL="$MOCK_BASE_URL/observability/collector/deployment/validate"
export MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_REQUIRED=true
export MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_URL="$MOCK_BASE_URL/observability/collector/cluster/validate"
export MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_REQUIRED=true
export MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_URL="$MOCK_BASE_URL/observability/remediation/run"
export MANDOFORGE_FINANCE_CLOSE_CONTROLLER_REQUIRED=true
export MANDOFORGE_FINANCE_CLOSE_CONTROLLER_URL="$MOCK_BASE_URL/finance/close"
export MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_REQUIRED=true
export MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_URL="$MOCK_BASE_URL/finance/reconcile"

if [[ "$RUN_DRILL_ACTIONS" == "1" ]]; then
  export RUN_STAGE2_SECRET_LIFECYCLE=1
  export RUN_STAGE2_PROVIDER_ROLLOUT=1
  export RUN_STAGE2_POLICY_DUE_RUN=1
  export RUN_STAGE2_REMOTE_SIDECAR_RECOVERY=1
  export RUN_STAGE2_APPROVAL_DELIVERY=1
  export RUN_STAGE2_CODEX_STALE_POLL=1
  export RUN_STAGE2_EVAL_RELEASE_AUTOMATION=1
  export RUN_STAGE2_OBSERVABILITY_REMEDIATION=1
  export RUN_STAGE2_FINANCE_CONTROLLERS=1
  export RUN_STAGE2_FINANCE_EXPORT=1
fi

./scripts/stage2-production-evidence-gate.sh
