#!/usr/bin/env bash
set -euo pipefail

template="deploy/stage2-evidence/stage2-production-controllers.env.example"
job_manifest="deploy/stage2-evidence/stage2-evidence-gate-job.yaml"

required_template_vars=(
  RUN_STAGE2_PRODUCTION_VALIDATIONS
  VERIFY_STAGE2_VALIDATION_COVERAGE
  ALLOW_BLOCKED
  MANDOFORGE_STAGE2_TEAM_ID
  MANDOFORGE_TENANT_ROUTING_CONTROLLER_REQUIRED
  MANDOFORGE_TENANT_ROUTING_CONTROLLER_URL
  MANDOFORGE_TENANT_ROUTING_CONTROLLER_TOKEN
  MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_PROVIDER_ROLLOUT_CONTROLLER_URL
  MANDOFORGE_PROVIDER_ROLLOUT_TOKEN
  MANDOFORGE_PROVIDER_ROLLOUT_ROLLBACK_CONTROLLER_URL
  MANDOFORGE_PROVIDER_ROLLOUT_ROLLBACK_TOKEN
  RUN_STAGE2_PROVIDER_ROLLOUT
  MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_REQUIRED
  MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_URL
  MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_TOKEN
  MANDOFORGE_KMS_PROVIDER
  MANDOFORGE_KMS_KEY_ID
  MANDOFORGE_KMS_ROTATION_POLICY
  MANDOFORGE_KMS_ENDPOINT
  MANDOFORGE_KMS_TOKEN
  MANDOFORGE_KMS_RECOVERY_CONTROLLER_REQUIRED
  MANDOFORGE_KMS_RECOVERY_CONTROLLER_URL
  MANDOFORGE_KMS_RECOVERY_CONTROLLER_TOKEN
  RUN_STAGE2_SECRET_LIFECYCLE
  MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_REQUIRED
  MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_URL
  MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_TOKEN
  MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_REQUIRED
  MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_URL
  MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_TOKEN
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_REPLACEMENT_ENABLED
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_REQUIRED
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_URL
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_TOKEN
  RUN_STAGE2_REMOTE_SIDECAR_RECOVERY
  MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_REQUIRED
  MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_URL
  MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_TOKEN
  RUN_STAGE2_APPROVAL_DELIVERY
  MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_MCP_ROLLOUT_CONTROLLER_REQUIRED
  MANDOFORGE_MCP_ROLLOUT_CONTROLLER_URL
  MANDOFORGE_MCP_ROLLOUT_CONTROLLER_TOKEN
  MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_REQUIRED
  MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_URL
  MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_TOKEN
  MANDOFORGE_CODEX_APP_SERVER_URL
  MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_REQUIRED
  MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_URL
  MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_TOKEN
  RUN_STAGE2_CODEX_STALE_POLL
  MANDOFORGE_AGENT_RELEASE_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_CONTROLLER_TOKEN
  MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_TOKEN
  MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_TOKEN
  RUN_STAGE2_EVAL_RELEASE_AUTOMATION
  MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_REQUIRED
  MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_URL
  MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_TOKEN
  MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_REQUIRED
  MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_URL
  MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_TOKEN
  RUN_STAGE2_OBSERVABILITY_REMEDIATION
  MANDOFORGE_FINANCE_CLOSE_CONTROLLER_REQUIRED
  MANDOFORGE_FINANCE_CLOSE_CONTROLLER_URL
  MANDOFORGE_FINANCE_CLOSE_CONTROLLER_TOKEN
  MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_REQUIRED
  MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_URL
  MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_TOKEN
  RUN_STAGE2_FINANCE_CONTROLLERS
)

required_job_flags=(
  RUN_STAGE2_PRODUCTION_VALIDATIONS
  RUN_STAGE2_SECRET_LIFECYCLE
  RUN_STAGE2_PROVIDER_ROLLOUT
  RUN_STAGE2_REMOTE_SIDECAR_RECOVERY
  RUN_STAGE2_APPROVAL_DELIVERY
  RUN_STAGE2_CODEX_STALE_POLL
  RUN_STAGE2_EVAL_RELEASE_AUTOMATION
  RUN_STAGE2_OBSERVABILITY_REMEDIATION
  RUN_STAGE2_FINANCE_CONTROLLERS
  VERIFY_STAGE2_VALIDATION_COVERAGE
)

if [[ ! -f "$template" ]]; then
  echo "missing Stage 2 controller env template: $template" >&2
  exit 1
fi

for var in "${required_template_vars[@]}"; do
  if ! grep -q "^${var}=" "$template"; then
    echo "Stage 2 controller env template is missing $var" >&2
    exit 1
  fi
done

if grep -E '(_TOKEN|_KEY_ID|MANDOFORGE_STAGE2_TEAM_ID)=.+' "$template" >/dev/null; then
  echo "Stage 2 controller env template must not contain real token, key, or team id values" >&2
  grep -nE '(_TOKEN|_KEY_ID|MANDOFORGE_STAGE2_TEAM_ID)=.+' "$template" >&2
  exit 1
fi

for flag in "${required_job_flags[@]}"; do
  if ! grep -q "name: ${flag}" "$job_manifest"; then
    echo "Stage 2 evidence Job is missing opt-in flag $flag" >&2
    exit 1
  fi
done

echo "stage2 controller env template ok"
