#!/usr/bin/env bash
set -euo pipefail

template="deploy/stage2-evidence/stage2-production-controllers.env.example"
job_manifest="deploy/stage2-evidence/stage2-evidence-gate-job.yaml"
secret_manifest="deploy/stage2-evidence/stage2-controller-env-secret.example.yaml"
production_job_manifest="deploy/stage2-evidence/stage2-production-evidence-gate-job.example.yaml"
render_secret_script="scripts/render-stage2-controller-secret.sh"
api_source="crates/mandoforge-api/src/main.rs"

required_template_vars=(
  RUN_STAGE2_PRODUCTION_VALIDATIONS
  VERIFY_STAGE2_VALIDATION_COVERAGE
  RUN_STAGE2_UI_ACTIONBOOK
  RUN_STAGE2_UI_STATIC_ASSETS
  ALLOW_BLOCKED
  MANDOFORGE_STAGE2_TEAM_ID
  MANDOFORGE_TENANT_ROUTING_CONTROLLER_REQUIRED
  MANDOFORGE_TENANT_ROUTING_CONTROLLER_URL
  MANDOFORGE_TENANT_ROUTING_CONTROLLER_TOKEN
  MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_PROVIDER_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_PROVIDER_ROLLOUT_CONTROLLER_URL
  MANDOFORGE_PROVIDER_ROLLOUT_TOKEN
  MANDOFORGE_PROVIDER_ROLLOUT_ROLLBACK_CONTROLLER_URL
  MANDOFORGE_PROVIDER_ROLLOUT_ROLLBACK_TOKEN
  RUN_STAGE2_PROVIDER_ROLLOUT
  MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_REQUIRED
  MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_URL
  MANDOFORGE_POLICY_ROLLOUT_ORCHESTRATION_CONTROLLER_TOKEN
  RUN_STAGE2_POLICY_DUE_RUN
  MANDOFORGE_KMS_PROVIDER
  MANDOFORGE_KMS_KEY_ID
  MANDOFORGE_KMS_ROTATION_POLICY
  MANDOFORGE_KMS_VALIDATION_MODE
  MANDOFORGE_KMS_TIMEOUT_SECONDS
  MANDOFORGE_KMS_ENDPOINT
  MANDOFORGE_KMS_TOKEN
  MANDOFORGE_KMS_RECOVERY_CONTROLLER_REQUIRED
  MANDOFORGE_KMS_RECOVERY_CONTROLLER_URL
  MANDOFORGE_KMS_RECOVERY_CONTROLLER_TOKEN
  RUN_STAGE2_SECRET_LIFECYCLE
  MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_REQUIRED
  MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_URL
  MANDOFORGE_WORKER_LOAD_VALIDATION_CONTROLLER_TOKEN
  MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_REQUIRED
  MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_URL
  MANDOFORGE_REMOTE_COMPUTER_STATE_SYNC_CONTROLLER_TOKEN
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_REPLACEMENT_ENABLED
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_REQUIRED
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_URL
  MANDOFORGE_REMOTE_COMPUTER_SIDECAR_VALIDATION_TOKEN
  RUN_STAGE2_REMOTE_SIDECAR_RECOVERY
  MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_APPROVAL_NOTIFICATION_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_REQUIRED
  MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_URL
  MANDOFORGE_APPROVAL_NOTIFICATION_OPS_CONTROLLER_TOKEN
  RUN_STAGE2_APPROVAL_DELIVERY
  MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_MCP_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_MCP_ROLLOUT_CONTROLLER_REQUIRED
  MANDOFORGE_MCP_ROLLOUT_CONTROLLER_URL
  MANDOFORGE_MCP_ROLLOUT_CONTROLLER_TOKEN
  MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_REQUIRED
  MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_URL
  MANDOFORGE_MCP_ROLLOUT_ROLLBACK_CONTROLLER_TOKEN
  RUN_STAGE2_MCP_DUE_RUN
  RUN_STAGE2_MCP_ROLLBACK
  MANDOFORGE_CODEX_APP_SERVER_URL
  MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_CODEX_APP_SERVER_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_REQUIRED
  MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_URL
  MANDOFORGE_CODEX_APP_SERVER_OPS_CONTROLLER_TOKEN
  RUN_STAGE2_CODEX_STALE_POLL
  MANDOFORGE_AGENT_RELEASE_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_CONTROLLER_TOKEN
  MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_ORCHESTRATION_CONTROLLER_TOKEN
  MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_REQUIRED
  MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_URL
  MANDOFORGE_AGENT_RELEASE_ROLLBACK_CONTROLLER_TOKEN
  RUN_STAGE2_EVAL_RELEASE_AUTOMATION
  RUN_STAGE2_EVAL_RELEASE_ROLLBACK
  MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_REQUIRED
  MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_URL
  MANDOFORGE_OBSERVABILITY_COLLECTOR_DEPLOYMENT_CONTROLLER_TOKEN
  MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_REQUIRED
  MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_URL
  MANDOFORGE_OBSERVABILITY_COLLECTOR_CLUSTER_CONTROLLER_TOKEN
  MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_REQUIRED
  MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_URL
  MANDOFORGE_OBSERVABILITY_REMEDIATION_CONTROLLER_TOKEN
  RUN_STAGE2_OBSERVABILITY_REMEDIATION
  MANDOFORGE_FINANCE_CLOSE_CONTROLLER_REQUIRED
  MANDOFORGE_FINANCE_CLOSE_CONTROLLER_URL
  MANDOFORGE_FINANCE_CLOSE_CONTROLLER_TOKEN
  MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_REQUIRED
  MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_URL
  MANDOFORGE_FINANCE_RECONCILIATION_CONTROLLER_TOKEN
  RUN_STAGE2_FINANCE_CONTROLLERS
  RUN_STAGE2_FINANCE_EXPORT
)

required_job_flags=(
  RUN_STAGE2_PRODUCTION_VALIDATIONS
  RUN_STAGE2_SECRET_LIFECYCLE
  RUN_STAGE2_PROVIDER_ROLLOUT
  RUN_STAGE2_REMOTE_SIDECAR_RECOVERY
  RUN_STAGE2_APPROVAL_DELIVERY
  RUN_STAGE2_CODEX_STALE_POLL
  RUN_STAGE2_EVAL_RELEASE_AUTOMATION
  RUN_STAGE2_OBSERVABILITY_REMEDIATION
  RUN_STAGE2_FINANCE_CONTROLLERS
  VERIFY_STAGE2_VALIDATION_COVERAGE
)

if [[ ! -f "$template" ]]; then
  echo "missing Stage 2 controller env template: $template" >&2
  exit 1
fi

if [[ ! -f "$secret_manifest" ]]; then
  echo "missing Stage 2 controller Secret example: $secret_manifest" >&2
  exit 1
fi

if [[ ! -f "$production_job_manifest" ]]; then
  echo "missing Stage 2 production evidence Job example: $production_job_manifest" >&2
  exit 1
fi

if [[ ! -x "$render_secret_script" ]]; then
  echo "missing executable Stage 2 controller Secret render script: $render_secret_script" >&2
  exit 1
fi

for var in "${required_template_vars[@]}"; do
  if ! grep -q "^${var}=" "$template"; then
    echo "Stage 2 controller env template is missing $var" >&2
    exit 1
  fi
  if ! grep -q "^  ${var}:" "$secret_manifest"; then
    echo "Stage 2 controller Secret example is missing $var" >&2
    exit 1
  fi
done

while IFS= read -r var; do
  if [[ -z "$var" || "$var" == *_TIMEOUT_SECONDS ]]; then
    continue
  fi
  if ! grep -q "^${var}=" "$template"; then
    echo "Stage 2 controller env template is missing source-referenced env $var" >&2
    exit 1
  fi
done < <(grep -Eho 'MANDOFORGE_[A-Z0-9_]*(CONTROLLER|KMS)[A-Z0-9_]*' "$api_source" | sort -u)

if grep -E '(_TOKEN|_KEY_ID|MANDOFORGE_STAGE2_TEAM_ID)=.+' "$template" >/dev/null; then
  echo "Stage 2 controller env template must not contain real token, key, or team id values" >&2
  grep -nE '(_TOKEN|_KEY_ID|MANDOFORGE_STAGE2_TEAM_ID)=.+' "$template" >&2
  exit 1
fi

if grep -E '(_TOKEN|_KEY_ID|MANDOFORGE_STAGE2_TEAM_ID): "[^"]+"' "$secret_manifest" >/dev/null; then
  echo "Stage 2 controller Secret example must not contain real token, key, or team id values" >&2
  grep -nE '(_TOKEN|_KEY_ID|MANDOFORGE_STAGE2_TEAM_ID): "[^"]+"' "$secret_manifest" >&2
  exit 1
fi

if grep -q 'MANDOFORGE_STAGE2_TEAM_ID|.*_TOKEN' "$render_secret_script"; then
  echo "Stage 2 controller Secret render must not require MANDOFORGE_STAGE2_TEAM_ID now that evidence gates auto-discover teams" >&2
  exit 1
fi

for flag in "${required_job_flags[@]}"; do
  if ! grep -q "name: ${flag}" "$job_manifest"; then
    echo "Stage 2 evidence Job is missing opt-in flag $flag" >&2
    exit 1
  fi
done

if ! grep -q "name: mandoforge-stage2-controller-env" "$production_job_manifest"; then
  echo "Stage 2 production evidence Job must consume mandoforge-stage2-controller-env" >&2
  exit 1
fi

if grep -q "name: RUN_STAGE2_PRODUCTION_VALIDATIONS" "$production_job_manifest"; then
  echo "Stage 2 production evidence Job should read validation flags from the Secret, not hard-coded env" >&2
  exit 1
fi

ALLOW_STAGE2_CONTROLLER_PLACEHOLDERS=1 "$render_secret_script" "$template" >/tmp/mandoforge-stage2-controller-secret-render.yaml

if ! grep -q "name: mandoforge-stage2-controller-env" /tmp/mandoforge-stage2-controller-secret-render.yaml; then
  echo "Stage 2 controller Secret render script produced the wrong Secret name" >&2
  exit 1
fi

if ! grep -q "MANDOFORGE_TENANT_ROUTING_CONTROLLER_URL" /tmp/mandoforge-stage2-controller-secret-render.yaml; then
  echo "Stage 2 controller Secret render is missing controller env data" >&2
  exit 1
fi

echo "stage2 controller env template ok"
